# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jakeclose/Desktop/398/project/eecs398-search

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jakeclose/Desktop/398/project/eecs398-search

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jakeclose/Desktop/398/project/eecs398-search/CMakeFiles /Users/jakeclose/Desktop/398/project/eecs398-search/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jakeclose/Desktop/398/project/eecs398-search/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named URLTEST

# Build rule for target.
URLTEST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 URLTEST
.PHONY : URLTEST

# fast build rule for target.
URLTEST/fast:
	$(MAKE) -f CMakeFiles/URLTEST.dir/build.make CMakeFiles/URLTEST.dir/build
.PHONY : URLTEST/fast

#=============================================================================
# Target rules for targets named StemmerTest

# Build rule for target.
StemmerTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StemmerTest
.PHONY : StemmerTest

# fast build rule for target.
StemmerTest/fast:
	$(MAKE) -f CMakeFiles/StemmerTest.dir/build.make CMakeFiles/StemmerTest.dir/build
.PHONY : StemmerTest/fast

#=============================================================================
# Target rules for targets named ParserEndToEndTest

# Build rule for target.
ParserEndToEndTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ParserEndToEndTest
.PHONY : ParserEndToEndTest

# fast build rule for target.
ParserEndToEndTest/fast:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/build
.PHONY : ParserEndToEndTest/fast

#=============================================================================
# Target rules for targets named TokenizerTest

# Build rule for target.
TokenizerTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TokenizerTest
.PHONY : TokenizerTest

# fast build rule for target.
TokenizerTest/fast:
	$(MAKE) -f CMakeFiles/TokenizerTest.dir/build.make CMakeFiles/TokenizerTest.dir/build
.PHONY : TokenizerTest/fast

#=============================================================================
# Target rules for targets named StringProcessingTest

# Build rule for target.
StringProcessingTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StringProcessingTest
.PHONY : StringProcessingTest

# fast build rule for target.
StringProcessingTest/fast:
	$(MAKE) -f CMakeFiles/StringProcessingTest.dir/build.make CMakeFiles/StringProcessingTest.dir/build
.PHONY : StringProcessingTest/fast

#=============================================================================
# Target rules for targets named search-engine

# Build rule for target.
search-engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 search-engine
.PHONY : search-engine

# fast build rule for target.
search-engine/fast:
	$(MAKE) -f CMakeFiles/search-engine.dir/build.make CMakeFiles/search-engine.dir/build
.PHONY : search-engine/fast

#=============================================================================
# Target rules for targets named crawler-parser-test

# Build rule for target.
crawler-parser-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crawler-parser-test
.PHONY : crawler-parser-test

# fast build rule for target.
crawler-parser-test/fast:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/build
.PHONY : crawler-parser-test/fast

crawler/SocketReader.o: crawler/SocketReader.cpp.o

.PHONY : crawler/SocketReader.o

# target to build an object file
crawler/SocketReader.cpp.o:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/crawler/SocketReader.cpp.o
.PHONY : crawler/SocketReader.cpp.o

crawler/SocketReader.i: crawler/SocketReader.cpp.i

.PHONY : crawler/SocketReader.i

# target to preprocess a source file
crawler/SocketReader.cpp.i:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/crawler/SocketReader.cpp.i
.PHONY : crawler/SocketReader.cpp.i

crawler/SocketReader.s: crawler/SocketReader.cpp.s

.PHONY : crawler/SocketReader.s

# target to generate assembly for a file
crawler/SocketReader.cpp.s:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/crawler/SocketReader.cpp.s
.PHONY : crawler/SocketReader.cpp.s

crawler/crawler.o: crawler/crawler.cpp.o

.PHONY : crawler/crawler.o

# target to build an object file
crawler/crawler.cpp.o:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/crawler/crawler.cpp.o
.PHONY : crawler/crawler.cpp.o

crawler/crawler.i: crawler/crawler.cpp.i

.PHONY : crawler/crawler.i

# target to preprocess a source file
crawler/crawler.cpp.i:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/crawler/crawler.cpp.i
.PHONY : crawler/crawler.cpp.i

crawler/crawler.s: crawler/crawler.cpp.s

.PHONY : crawler/crawler.s

# target to generate assembly for a file
crawler/crawler.cpp.s:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/crawler/crawler.cpp.s
.PHONY : crawler/crawler.cpp.s

crawler/spider.o: crawler/spider.cpp.o

.PHONY : crawler/spider.o

# target to build an object file
crawler/spider.cpp.o:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/crawler/spider.cpp.o
.PHONY : crawler/spider.cpp.o

crawler/spider.i: crawler/spider.cpp.i

.PHONY : crawler/spider.i

# target to preprocess a source file
crawler/spider.cpp.i:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/crawler/spider.cpp.i
.PHONY : crawler/spider.cpp.i

crawler/spider.s: crawler/spider.cpp.s

.PHONY : crawler/spider.s

# target to generate assembly for a file
crawler/spider.cpp.s:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/crawler/spider.cpp.s
.PHONY : crawler/spider.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/main.cpp.s
.PHONY : main.cpp.s

parser/Parser.o: parser/Parser.cpp.o

.PHONY : parser/Parser.o

# target to build an object file
parser/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/parser/Parser.cpp.o
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/parser/Parser.cpp.o
.PHONY : parser/Parser.cpp.o

parser/Parser.i: parser/Parser.cpp.i

.PHONY : parser/Parser.i

# target to preprocess a source file
parser/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/parser/Parser.cpp.i
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/parser/Parser.cpp.i
.PHONY : parser/Parser.cpp.i

parser/Parser.s: parser/Parser.cpp.s

.PHONY : parser/Parser.s

# target to generate assembly for a file
parser/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/parser/Parser.cpp.s
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/parser/Parser.cpp.s
.PHONY : parser/Parser.cpp.s

parser/tests/parserTest.o: parser/tests/parserTest.cpp.o

.PHONY : parser/tests/parserTest.o

# target to build an object file
parser/tests/parserTest.cpp.o:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/parser/tests/parserTest.cpp.o
.PHONY : parser/tests/parserTest.cpp.o

parser/tests/parserTest.i: parser/tests/parserTest.cpp.i

.PHONY : parser/tests/parserTest.i

# target to preprocess a source file
parser/tests/parserTest.cpp.i:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/parser/tests/parserTest.cpp.i
.PHONY : parser/tests/parserTest.cpp.i

parser/tests/parserTest.s: parser/tests/parserTest.cpp.s

.PHONY : parser/tests/parserTest.s

# target to generate assembly for a file
parser/tests/parserTest.cpp.s:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/parser/tests/parserTest.cpp.s
.PHONY : parser/tests/parserTest.cpp.s

query/Query.o: query/Query.cpp.o

.PHONY : query/Query.o

# target to build an object file
query/Query.cpp.o:
	$(MAKE) -f CMakeFiles/search-engine.dir/build.make CMakeFiles/search-engine.dir/query/Query.cpp.o
.PHONY : query/Query.cpp.o

query/Query.i: query/Query.cpp.i

.PHONY : query/Query.i

# target to preprocess a source file
query/Query.cpp.i:
	$(MAKE) -f CMakeFiles/search-engine.dir/build.make CMakeFiles/search-engine.dir/query/Query.cpp.i
.PHONY : query/Query.cpp.i

query/Query.s: query/Query.cpp.s

.PHONY : query/Query.s

# target to generate assembly for a file
query/Query.cpp.s:
	$(MAKE) -f CMakeFiles/search-engine.dir/build.make CMakeFiles/search-engine.dir/query/Query.cpp.s
.PHONY : query/Query.cpp.s

search.o: search.cpp.o

.PHONY : search.o

# target to build an object file
search.cpp.o:
	$(MAKE) -f CMakeFiles/search-engine.dir/build.make CMakeFiles/search-engine.dir/search.cpp.o
.PHONY : search.cpp.o

search.i: search.cpp.i

.PHONY : search.i

# target to preprocess a source file
search.cpp.i:
	$(MAKE) -f CMakeFiles/search-engine.dir/build.make CMakeFiles/search-engine.dir/search.cpp.i
.PHONY : search.cpp.i

search.s: search.cpp.s

.PHONY : search.s

# target to generate assembly for a file
search.cpp.s:
	$(MAKE) -f CMakeFiles/search-engine.dir/build.make CMakeFiles/search-engine.dir/search.cpp.s
.PHONY : search.cpp.s

shared/Document.o: shared/Document.cpp.o

.PHONY : shared/Document.o

# target to build an object file
shared/Document.cpp.o:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/shared/Document.cpp.o
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/shared/Document.cpp.o
.PHONY : shared/Document.cpp.o

shared/Document.i: shared/Document.cpp.i

.PHONY : shared/Document.i

# target to preprocess a source file
shared/Document.cpp.i:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/shared/Document.cpp.i
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/shared/Document.cpp.i
.PHONY : shared/Document.cpp.i

shared/Document.s: shared/Document.cpp.s

.PHONY : shared/Document.s

# target to generate assembly for a file
shared/Document.cpp.s:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/shared/Document.cpp.s
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/shared/Document.cpp.s
.PHONY : shared/Document.cpp.s

shared/urlTest.o: shared/urlTest.cpp.o

.PHONY : shared/urlTest.o

# target to build an object file
shared/urlTest.cpp.o:
	$(MAKE) -f CMakeFiles/URLTEST.dir/build.make CMakeFiles/URLTEST.dir/shared/urlTest.cpp.o
.PHONY : shared/urlTest.cpp.o

shared/urlTest.i: shared/urlTest.cpp.i

.PHONY : shared/urlTest.i

# target to preprocess a source file
shared/urlTest.cpp.i:
	$(MAKE) -f CMakeFiles/URLTEST.dir/build.make CMakeFiles/URLTEST.dir/shared/urlTest.cpp.i
.PHONY : shared/urlTest.cpp.i

shared/urlTest.s: shared/urlTest.cpp.s

.PHONY : shared/urlTest.s

# target to generate assembly for a file
shared/urlTest.cpp.s:
	$(MAKE) -f CMakeFiles/URLTEST.dir/build.make CMakeFiles/URLTEST.dir/shared/urlTest.cpp.s
.PHONY : shared/urlTest.cpp.s

util/stringProcessing.o: util/stringProcessing.cpp.o

.PHONY : util/stringProcessing.o

# target to build an object file
util/stringProcessing.cpp.o:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/util/stringProcessing.cpp.o
	$(MAKE) -f CMakeFiles/StringProcessingTest.dir/build.make CMakeFiles/StringProcessingTest.dir/util/stringProcessing.cpp.o
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/util/stringProcessing.cpp.o
.PHONY : util/stringProcessing.cpp.o

util/stringProcessing.i: util/stringProcessing.cpp.i

.PHONY : util/stringProcessing.i

# target to preprocess a source file
util/stringProcessing.cpp.i:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/util/stringProcessing.cpp.i
	$(MAKE) -f CMakeFiles/StringProcessingTest.dir/build.make CMakeFiles/StringProcessingTest.dir/util/stringProcessing.cpp.i
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/util/stringProcessing.cpp.i
.PHONY : util/stringProcessing.cpp.i

util/stringProcessing.s: util/stringProcessing.cpp.s

.PHONY : util/stringProcessing.s

# target to generate assembly for a file
util/stringProcessing.cpp.s:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/util/stringProcessing.cpp.s
	$(MAKE) -f CMakeFiles/StringProcessingTest.dir/build.make CMakeFiles/StringProcessingTest.dir/util/stringProcessing.cpp.s
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/util/stringProcessing.cpp.s
.PHONY : util/stringProcessing.cpp.s

util/tests/stemmerTest.o: util/tests/stemmerTest.cpp.o

.PHONY : util/tests/stemmerTest.o

# target to build an object file
util/tests/stemmerTest.cpp.o:
	$(MAKE) -f CMakeFiles/StemmerTest.dir/build.make CMakeFiles/StemmerTest.dir/util/tests/stemmerTest.cpp.o
.PHONY : util/tests/stemmerTest.cpp.o

util/tests/stemmerTest.i: util/tests/stemmerTest.cpp.i

.PHONY : util/tests/stemmerTest.i

# target to preprocess a source file
util/tests/stemmerTest.cpp.i:
	$(MAKE) -f CMakeFiles/StemmerTest.dir/build.make CMakeFiles/StemmerTest.dir/util/tests/stemmerTest.cpp.i
.PHONY : util/tests/stemmerTest.cpp.i

util/tests/stemmerTest.s: util/tests/stemmerTest.cpp.s

.PHONY : util/tests/stemmerTest.s

# target to generate assembly for a file
util/tests/stemmerTest.cpp.s:
	$(MAKE) -f CMakeFiles/StemmerTest.dir/build.make CMakeFiles/StemmerTest.dir/util/tests/stemmerTest.cpp.s
.PHONY : util/tests/stemmerTest.cpp.s

util/tests/stringProcessingTest.o: util/tests/stringProcessingTest.cpp.o

.PHONY : util/tests/stringProcessingTest.o

# target to build an object file
util/tests/stringProcessingTest.cpp.o:
	$(MAKE) -f CMakeFiles/StringProcessingTest.dir/build.make CMakeFiles/StringProcessingTest.dir/util/tests/stringProcessingTest.cpp.o
.PHONY : util/tests/stringProcessingTest.cpp.o

util/tests/stringProcessingTest.i: util/tests/stringProcessingTest.cpp.i

.PHONY : util/tests/stringProcessingTest.i

# target to preprocess a source file
util/tests/stringProcessingTest.cpp.i:
	$(MAKE) -f CMakeFiles/StringProcessingTest.dir/build.make CMakeFiles/StringProcessingTest.dir/util/tests/stringProcessingTest.cpp.i
.PHONY : util/tests/stringProcessingTest.cpp.i

util/tests/stringProcessingTest.s: util/tests/stringProcessingTest.cpp.s

.PHONY : util/tests/stringProcessingTest.s

# target to generate assembly for a file
util/tests/stringProcessingTest.cpp.s:
	$(MAKE) -f CMakeFiles/StringProcessingTest.dir/build.make CMakeFiles/StringProcessingTest.dir/util/tests/stringProcessingTest.cpp.s
.PHONY : util/tests/stringProcessingTest.cpp.s

util/tests/tokenizerTest.o: util/tests/tokenizerTest.cpp.o

.PHONY : util/tests/tokenizerTest.o

# target to build an object file
util/tests/tokenizerTest.cpp.o:
	$(MAKE) -f CMakeFiles/TokenizerTest.dir/build.make CMakeFiles/TokenizerTest.dir/util/tests/tokenizerTest.cpp.o
.PHONY : util/tests/tokenizerTest.cpp.o

util/tests/tokenizerTest.i: util/tests/tokenizerTest.cpp.i

.PHONY : util/tests/tokenizerTest.i

# target to preprocess a source file
util/tests/tokenizerTest.cpp.i:
	$(MAKE) -f CMakeFiles/TokenizerTest.dir/build.make CMakeFiles/TokenizerTest.dir/util/tests/tokenizerTest.cpp.i
.PHONY : util/tests/tokenizerTest.cpp.i

util/tests/tokenizerTest.s: util/tests/tokenizerTest.cpp.s

.PHONY : util/tests/tokenizerTest.s

# target to generate assembly for a file
util/tests/tokenizerTest.cpp.s:
	$(MAKE) -f CMakeFiles/TokenizerTest.dir/build.make CMakeFiles/TokenizerTest.dir/util/tests/tokenizerTest.cpp.s
.PHONY : util/tests/tokenizerTest.cpp.s

util/util.o: util/util.cpp.o

.PHONY : util/util.o

# target to build an object file
util/util.cpp.o:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/util/util.cpp.o
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/util/util.cpp.o
.PHONY : util/util.cpp.o

util/util.i: util/util.cpp.i

.PHONY : util/util.i

# target to preprocess a source file
util/util.cpp.i:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/util/util.cpp.i
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/util/util.cpp.i
.PHONY : util/util.cpp.i

util/util.s: util/util.cpp.s

.PHONY : util/util.s

# target to generate assembly for a file
util/util.cpp.s:
	$(MAKE) -f CMakeFiles/ParserEndToEndTest.dir/build.make CMakeFiles/ParserEndToEndTest.dir/util/util.cpp.s
	$(MAKE) -f CMakeFiles/crawler-parser-test.dir/build.make CMakeFiles/crawler-parser-test.dir/util/util.cpp.s
.PHONY : util/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... URLTEST"
	@echo "... rebuild_cache"
	@echo "... StemmerTest"
	@echo "... ParserEndToEndTest"
	@echo "... TokenizerTest"
	@echo "... StringProcessingTest"
	@echo "... search-engine"
	@echo "... crawler-parser-test"
	@echo "... crawler/SocketReader.o"
	@echo "... crawler/SocketReader.i"
	@echo "... crawler/SocketReader.s"
	@echo "... crawler/crawler.o"
	@echo "... crawler/crawler.i"
	@echo "... crawler/crawler.s"
	@echo "... crawler/spider.o"
	@echo "... crawler/spider.i"
	@echo "... crawler/spider.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser/Parser.o"
	@echo "... parser/Parser.i"
	@echo "... parser/Parser.s"
	@echo "... parser/tests/parserTest.o"
	@echo "... parser/tests/parserTest.i"
	@echo "... parser/tests/parserTest.s"
	@echo "... query/Query.o"
	@echo "... query/Query.i"
	@echo "... query/Query.s"
	@echo "... search.o"
	@echo "... search.i"
	@echo "... search.s"
	@echo "... shared/Document.o"
	@echo "... shared/Document.i"
	@echo "... shared/Document.s"
	@echo "... shared/urlTest.o"
	@echo "... shared/urlTest.i"
	@echo "... shared/urlTest.s"
	@echo "... util/stringProcessing.o"
	@echo "... util/stringProcessing.i"
	@echo "... util/stringProcessing.s"
	@echo "... util/tests/stemmerTest.o"
	@echo "... util/tests/stemmerTest.i"
	@echo "... util/tests/stemmerTest.s"
	@echo "... util/tests/stringProcessingTest.o"
	@echo "... util/tests/stringProcessingTest.i"
	@echo "... util/tests/stringProcessingTest.s"
	@echo "... util/tests/tokenizerTest.o"
	@echo "... util/tests/tokenizerTest.i"
	@echo "... util/tests/tokenizerTest.s"
	@echo "... util/util.o"
	@echo "... util/util.i"
	@echo "... util/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

