//
// Created by Ben Bergkamp on 1/25/18.
//

#ifndef EECS398_SEARCH_PRODUCERCONSUMERQUEUE_H
#define EECS398_SEARCH_PRODUCERCONSUMERQUEUE_H


class ProducerConsumerQueue {

};


#endif //EECS398_SEARCH_PRODUCERCONSUMERQUEUE_H
